### ISSUE TITLE
link 404s on readme

### ISSUE THREAD

**Issue by tayzlor** [Capgemini/dtx-polyfiller#1]
https://github.com/Capgemini/dtx-polyfiller/blob/master/dtx-polyfiller/dtx-polyfiller.crx

**Comment by tim-holbrook** [comment]
More specifically, the Install/Download link is broken and the crx won't download

**Comment by malcomio** [comment]
this was fixed by #2, wasn't it?

**Comment by lutnos** [comment]
I think that this works when on branch gh-pages, but not on master.  So as long as the .crx for that branch is acceptable, then this link is downloadable:  https://github.com/Capgemini/dtx-polyfiller/blob/gh-pages/dtx-polyfiller.crx

**Comment by daniel-cotton** [comment]
Closing via #8
